language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r tests-requirements.txt
# command to run tests
script:
# TODO Create python tests
# - pytest
  - pylama
